#!/bin/sh

SCRIPT="/usr/share/opendict/opendict.py"
OPTIONS="--splash"

if [ -f $SCRIPT ]; then
   echo "Running OpenDict..."
   python $SCRIPT $OPTIONS > /tmp/opendict-output-`id -u -n`  2>&1
else
   echo "Error: OpenDict system-wide installation not found."
   exit
fi
